version: "3.1"

services:
  web:
    image: mallorca-magic-backend
    build: .
    command: gunicorn -b 0.0.0.0:8000 -w 5 --threads 16 --preload mallorcamagicBackend.wsgi:application
    volumes:
      - .:/code
    ports:
      - 8000:8000

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rgqeRAk2!Z2aWc8X
      ME_CONFIG_MONGODB_URL: mongodb://root:rgqeRAk2!Z2aWc8X@178.62.216.217:27017,207.154.254.241:27018,207.154.254.241:27019/?authSource=admin&replicaSet=rs0
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: (8zd5SbhuVJ)Q2v!