# Generated by Django 3.2.9 on 2022-05-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_data', '0002_remove_savedguide_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedguide',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
