# Generated by Django 4.0.4 on 2022-08-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='description_de',
            field=models.TextField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='description_es',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='slug_de',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='slug_es',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='title_de',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='title_es',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
